force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_Date__c</fullName>
    <description>Date when the Project should be finished(Estimate)</description>
    <label>Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangProjStatusBasedOnTasksStatusesTest.cls
@isTest
public class ChangProjStatusBasedOnTasksStatusesTest {
    
    static final String Maintest_Project_Name    = 'MainTestProject';
    static final Date DATE_TODAY                 = System.today();

    @testSetup
    static void setup() {

        Project__c project = TestDataFactory.createProject(Maintest_Project_Name);    
        project.Planned_End_Date__c = DATE_TODAY;
        project.Status__c = '';

        insert project;
    }    

    @isTest
    public static void testAllStatusesDraft(){

        Project__c project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];
        
        System.assert(String.isBlank(project.Status__c), 'Project status must be empty');


        List<Task__c> tasks = TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Draft, DATE_TODAY);

        Test.startTest();
            Database.SaveResult[] srList = Database.insert(tasks, false);
        Test.stopTest();


        project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];


        System.assertEquals(ToDoListService.Project_Status_Draft, 
                                project.Status__c, 'Wrong project status when all tasks statuses are equal to Draft');
    }

    @isTest
    public static void testAllStatusCompletedAndFinishedInTime(){

        Project__c project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];
        
        System.assert(String.isBlank(project.Status__c), 'Project status must be empty');


        List<Task__c> tasks = TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Completed, DATE_TODAY);

        Test.startTest();
            Database.SaveResult[] srList = Database.insert(tasks, false);
        Test.stopTest();


        project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];

        System.assertEquals(ToDoListService.Project_Status_FinishedInTime, 
                                project.Status__c, 'Wrong project status when all tasks are finished in time');
    }

    @isTest
    public static void testAllStatusCompletedAndFinishedWithDelay(){

        Project__c project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];
        
        System.assert(String.isBlank(project.Status__c), 'Project status must be empty');


        List<Task__c> tasks = TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Completed, DATE_TODAY);
            tasks.add(
                TestDataFactory.createStandardTask(project.Id, null, ToDoListService.Task_Status_Completed, DATE_TODAY.addDays(10))
            );

        Test.startTest();
            Database.SaveResult[] srList = Database.insert(tasks, false);
        Test.stopTest();


        project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];

    
        System.assertEquals(ToDoListService.Project_Status_FinishedWithDelay, 
                                project.Status__c, 'Wrong project status when one task is finished with delay');
    }

    @isTest
    public static void testOneTaskStatusStarted(){

        Project__c project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];
        
        System.assert(String.isBlank(project.Status__c), 'Project status must be empty');

        List<Task__c> tasks = TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Draft, DATE_TODAY);

            tasks.addAll(
                TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Completed, DATE_TODAY)
            );
            
            tasks.add(
                TestDataFactory.createStandardTask(project.Id, null, ToDoListService.Task_Status_Started, DATE_TODAY)
            );

        
        Test.startTest();
            Database.SaveResult[] srList = Database.insert(tasks, false);
        Test.stopTest();


        project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];    

        System.assertEquals(ToDoListService.Project_Status_InProgress, 
                                project.Status__c, 'Wrong project status when any task is Started');
    }

    @isTest
    public static void testOtherCases(){

        Project__c project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];
        
        System.assert(String.isBlank(project.Status__c), 'Project status must be empty');


        List<Task__c> tasks = TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Draft, DATE_TODAY);

            tasks.addAll(
                TestDataFactory.createTasksForProject(project.Id, null, 5, ToDoListService.Task_Status_Completed, DATE_TODAY)
            );

            tasks.add(
                TestDataFactory.createStandardTask(project.Id, null, ToDoListService.Task_Status_Completed, DATE_TODAY.addDays(10))
            );


        Test.startTest();
            Database.SaveResult[] srList = Database.insert(tasks, false);
        Test.stopTest();    


        project = [SELECT Id, Status__c FROM Project__c WHERE Name =: Maintest_Project_Name LIMIT 1];

        System.assertEquals(ToDoListService.Project_Status_Draft, 
                                project.Status__c, 'Wrong project status by default');
    }

}