force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoListServiceTest.cls
@isTest
public class ToDoListServiceTest {
    
    @testSetup
    static void setup() {

        Project__c project = new Project__c(name = 'Main Test Project');
        insert project;


        List<Task__c> tasks = new List<Task__c>();

        for (Integer i=0; i<10; i++) {
            tasks.add(new Task__c(Project__c = project.id, Status__c = 'Draft'));
        }

        for (Integer i=0; i<5; i++) {
            tasks.add(new Task__c(Project__c = project.id, Status__c = 'Completed', End_Date__c = Date.today()));
        }
        tasks.add(new Task__c(Project__c = project.id, Status__c = 'Completed', End_Date__c = Date.today().addDays(10)));
        
        tasks.add(new Task__c(Project__c = project.id, Status__c = 'Started'));
        
        
        insert tasks;

    }

    @isTest
    public static void testAllStatusesDraft(){

        List<Task__c> tasks = [SELECT Id, Name, Status__c, End_Date__c FROM Task__c WHERE Status__c = 'Draft'];

        String status = ToDoListService.getProjectStatus(tasks, Date.today());

        System.assertEquals('Draft', status, 'Wrong project status when all tasks statuses are equal to Draft');
    }

    @isTest
    public static void testAllStatusCompletedAndFinishedInTime(){

        List<Task__c> tasks = [SELECT Id, Name, Status__c, End_Date__c FROM Task__c WHERE Status__c = 'Completed' AND End_Date__c <= TODAY];

        String status = ToDoListService.getProjectStatus(tasks, Date.today());

        System.assertEquals('Finished in Time', status, 'Wrong project status when all tasks are finished in time');
    }

    @isTest
    public static void testAllStatusCompletedAndFinishedWithDelay(){

        List<Task__c> tasks = [SELECT Id, Status__c, End_Date__c FROM Task__c WHERE Status__c = 'Completed'];
        
        String status = ToDoListService.getProjectStatus(tasks, Date.today());
    
        System.assertEquals('Finished with Delay', status, 'Wrong project status when one task is finished with delay');
    }

    @isTest
    public static void testOneTaskStatusStarted(){

        List<Task__c> tasks = [SELECT Id, Name, Status__c, End_Date__c FROM Task__c];

        String status = ToDoListService.getProjectStatus(tasks, Date.today());

        System.assertEquals('In Progress', status, 'Wrong project status when any task is Started');
    }

    @isTest
    public static void testOtherCases(){

        List<Task__c> tasks = [SELECT Id, Name, Status__c, End_Date__c FROM Task__c WHERE Status__c != 'Started'];

        String status = ToDoListService.getProjectStatus(tasks, Date.today());

        System.assertEquals('Draft', status, 'Wrong project status by default');
    }

}