force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectTriggerHandler.cls
public class ProjectTriggerHandler {
   
    private static Set<Id> personsIds;

    public static void onBeforeDelete(List<Project__c> oldProjects){

        Set<Id> projectsIds = new Set<Id>();

        for(Project__c project : oldProjects){
            projectsIds.add(project.Id);    
        }
        
        Set<Id> personsIds = new Set<Id>();
        for(Task__c task : [SELECT Person__c FROM Task__c WHERE Project__c IN : projectsIds]){
            personsIds.add(task.Person__c);    
        }

        ProjectTriggerHandler.personsIds = personsIds;

    }

    public static void onAfterDelete(){

        TaskTriggerHandler.calculatTotalTasksAndTotalProjectsOfPerson(personsIds);

    }

    



}