force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Project will start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Task Name</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Task is planned to start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PersonController.cls
public class PersonController {
  
    @AuraEnabled(cacheable=true)
    public static List<PersonWrapper> getBestPersonsWhoFinishedInTime(Integer personsNumber) {
        
        List<PersonWrapper> personWrappers = new List<PersonWrapper>();


        AggregateResult[] groupedFiveBiggestProjects = [SELECT Person__c personId, Person__r.First_Name__c firstName, Person__r.Last_Name__c lastName, COUNT_DISTINCT(Project__c)projectCount  
                                    	                FROM Task__c
                                                		WHERE Project__r.Status__c =: ToDoListService.Project_Status_FinishedInTime
                                    	                GROUP BY Person__c, Person__r.First_Name__c, Person__r.Last_Name__c  
                                    	                ORDER BY COUNT_DISTINCT(Project__c) DESC 
                                    	                LIMIT :personsNumber];
        for (AggregateResult ar : groupedFiveBiggestProjects)  {
            personWrappers.add(
                new PersonWrapper(String.valueOf(ar.get('personId')),
                                  String.valueOf(ar.get('firstName')) + ' ' + String.valueOf(ar.get('lastName')),
                                  Integer.valueOf(ar.get('projectCount')))
                );
        }

        return personWrappers;   
    }

    @AuraEnabled(cacheable=true)
    public static List<TaskWrapper> getUpcomingPersonTasks(ID personId) {
        
        List<TaskWrapper> taskWrappers = new List<TaskWrapper>();

        for(Task__c task: [SELECT Id, Project__r.Name, Label__c, Start_Date__c, End_Date__c, Status__c 
                           FROM Task__c 
                           WHERE Person__c =: personId
                                AND Status__c =: ToDoListService.Task_Status_Draft
                           ORDER BY Start_Date__c]){

            taskWrappers.add(
                new TaskWrapper(task.Id,
                                task.Project__r.Name,
                                task.Label__c,
                                task.Start_Date__c,
                                task.End_Date__c,
                                task.Status__c)
            );
        }

        return taskWrappers;
    }


    public class PersonWrapper{
        
        @AuraEnabled
        public Id personId{get;set;}

        @AuraEnabled
        public String personFullName{get;set;}
        
        @AuraEnabled
        public Integer numberOfProjects{get;set;}

        public PersonWrapper(String personId, String personFullName, Integer numberOfProjects) {
            this.personId           = personId;
            this.personFullName     = personFullName;
            this.numberOfProjects  = numberOfProjects;
        }
    }


    public class TaskWrapper{

        @AuraEnabled
        public Id taskId{get;set;}

        @AuraEnabled
        public String projectName{get;set;}
        
        @AuraEnabled
        public String taskLabel{get;set;}
        
        @AuraEnabled
        public Date taskStartDate{get;set;}

        @AuraEnabled
        public Date taskEndDate{get;set;}

        @AuraEnabled
        public String taskStatus{get;set;}

        public TaskWrapper(Id taskId, String projectName, String taskLabel, Date taskStartDate, Date taskEndDate, String taskStatus) {
            this.taskId         = taskId;
            this.projectName    = projectName;
            this.taskLabel      = taskLabel;
            this.taskStartDate  = taskStartDate;
            this.taskEndDate    = taskEndDate;
            this.taskStatus     = taskStatus;
        }
    }
    
}