force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Is_Synced__c.field-meta.xml
<CustomField>
    <fullName>Is_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Synchronization status</description>
    <label>Is Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Projects__c</fullName>
    <description>Total amount of Projects assigned to Person</description>
    <label>Total Amount of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Tasks__c</fullName>
    <description>Total amount of Tasks assigned to Person</description>
    <label>Total Amount of Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoListDAO.cls
public class ToDoListDAO {
    
    public static Person__c getPerson(Id personId){

        return [SELECT Id, First_Name__c, Last_Name__c, Is_Synced__c, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c
                FROM Person__c
                WHERE Id =:personId];

    }
    
    public static Map<Id, List<Task__c>> getOverdueTasksByProjectIds(Set<Id> personIds){

        Map<Id, List<Task__c>> tasksByProjectIds = new Map<Id, List<Task__c>>();

            for(Task__c task: [SELECT Id, Name, Project__c  FROM Task__c 
                                                                WHERE Person__c IN : personIds 
                                                                    AND Status__c = 'Started'  
                                                                        AND End_Date__c <= TODAY]){
                                    
        
                List<Task__c> tasks = tasksByProjectIds.get(task.Project__c);
                                        
                if(tasks == null) {
                    tasksByProjectIds.put(task.Project__c, new List<Task__c>{task});
                }else {
                    tasks.add(task);    
                }     
            }

       return tasksByProjectIds; 
    }

    public static Map<Id, Set<Id>> getProjectsByPersonsIds(Set<Id> personIds){

        Map<Id, Set<Id>> projectsByPersonsIds = new Map<Id, Set<Id>>();
        
        for(Task__c task: [SELECT Id, Project__c, Person__c FROM Task__c WHERE Person__c IN : personIds]){

            Set<Id> projectsIds = projectsByPersonsIds.get(task.Person__c);

            if(projectsIds == null){
                projectsByPersonsIds.put(task.Person__c, new Set<Id>{task.Project__c});
            }else {
                projectsIds.add(task.Project__c);   
            }
        }

        return projectsByPersonsIds;
    }

    public static List<Project__c> getFiveBiggestProjects(){

        AggregateResult[] groupedFiveBiggestProjects = [SELECT Project__c, COUNT_DISTINCT(Person__c)PersonCount  
                                    	                FROM Task__c 
                                    	                GROUP BY Project__c 
                                    	                ORDER BY COUNT_DISTINCT(Person__c) DESC 
                                    	                LIMIT 5];
        Set<Id> projectsIds = new Set<Id>();

        for (AggregateResult ar : groupedFiveBiggestProjects)  {
            
            //System.debug('Project:' + ar.get('Project__c') + ' ' + 'Person count:' + ar.get('PersonCount'));
            
			projectsIds.add(String.valueOf(ar.get('Project__c')));
        }

        return [SELECT Id, Name, Status__c FROM Project__c WHERE Id IN : projectsIds];
    }

}