force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataUtils.cls
public class TestDataUtils {
    
    public static void deleteTasksFromProjects(Integer numProjects, Integer numTasksOfProj, Id personId){

        List<Task__c> tasks = new List<Task__c>();

        for(Project__c project : [SELECT Id, (SELECT Id FROM Tasks__r WHERE Person__c =: personId LIMIT :numTasksOfProj) 
                                    FROM Project__c 
                                    LIMIT : numProjects]){

            tasks.addAll(project.Tasks__r);
        }

        delete tasks;
    }

    public static void deletePersonsFromTasks(Id personId){

        List<Task__c> tasks = [SELECT Id, Person__c FROM Task__c WHERE Person__c =: personId];


        for(Task__c task : tasks){
            task.Person__c = null;    
        }

        update tasks;
    }

    public static List<Task__c> changePersonInTasks(List<Task__c> tasks, Id newPersonId){

        for(Task__c task : tasks){
            task.Person__c = newPersonId;    
        }

        return tasks;
    }

    


}