force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Projects__c</fullName>
    <description>Total amount of Projects assigned to Person</description>
    <label>Total Amount of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Tasks__c</fullName>
    <description>Total amount of Tasks assigned to Person</description>
    <label>Total Amount of Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Planned_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_Date__c</fullName>
    <description>Date when the Project should be finished(Estimate)</description>
    <label>Planned End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public class TaskTriggerHandler {

    public static void onBeforeUpdate(List<Task__c> newTasks, Map<Id, Task__c> oldTasksMap){

        checkPersonChangeInCompletedTasks(newTasks, oldTasksMap);    
    }

    public static void onAfterInsert(List<Task__c> newTasks){

        calculatTotalTasksAndTotalProjectsOfPerson(getPersonsIds(newTasks));

        setProjectStatusesBasedOnTasks(getProjectsIds(newTasks));
    }

    public static void onAfterUpdate(List<Task__c> newTasks, List<Task__c> oldTasks){
        
        Set<Id> personsIds = getPersonsIds(newTasks);
        personsIds.addAll(getPersonsIds(oldTasks));
        
        calculatTotalTasksAndTotalProjectsOfPerson(personsIds);

        setProjectStatusesBasedOnTasks(getProjectsIds(newTasks));    
    }

    public static void onAfterDelete(List<Task__c> oldTasks){

        calculatTotalTasksAndTotalProjectsOfPerson(getPersonsIds(oldTasks));

        setProjectStatusesBasedOnTasks(getProjectsIds(oldTasks));
    }

    public static void checkPersonChangeInCompletedTasks(List<Task__c> newTasks, Map<Id, Task__c> oldTasksMap){

        for (Task__c task : newTasks) {
            
            if(task.Status__c != ToDoListService.Task_Status_Completed)
                continue;
            

            Task__c oldTask = oldTasksMap.get(task.Id);
            if(task.Person__c <> oldTask.Person__c){
                task.Person__c.addError('Сan\'t change the personа of a completed task');
            }
        }
    }

    public static void calculatTotalTasksAndTotalProjectsOfPerson(Set<Id> personsIds) {

        if(personsIds.size() == 0){
            return;
        }
        
        List<Person__c> personsToUpdate = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c  
                                                                    FROM Person__c 
                                                                    WHERE Id IN : personsIds];

        
        Map<Id, Set<Id>> personsIdsToProjectsIds = new Map<Id, Set<Id>>();
        Map<Id, Set<Id>> personsIdsToTasksIds = new Map<Id, Set<Id>>();                                                            
        for(Task__c task : [SELECT Id, Person__c, Project__c FROM Task__c WHERE Person__c IN : personsIds]){

            if (personsIdsToProjectsIds.containsKey(task.Person__c)) {
                personsIdsToProjectsIds.get(task.Person__c).add(task.Project__c);
            } else {
                personsIdsToProjectsIds.put(
                    task.Person__c,
                    new Set<Id>{ task.Project__c }
                );
            }

            if (personsIdsToTasksIds.containsKey(task.Person__c)) {
                personsIdsToTasksIds.get(task.Person__c).add(task.Id);
            } else {
                personsIdsToTasksIds.put(
                    task.Person__c,
                    new Set<Id>{ task.Id }
                );
            } 
        }



        for(Person__c person : personsToUpdate){
            
            if (personsIdsToProjectsIds.containsKey(person.Id)) {
                person.Total_Amount_of_Projects__c = personsIdsToProjectsIds.get(person.Id).size();
            }else {
                person.Total_Amount_of_Projects__c = 0;        
            }

            if (personsIdsToTasksIds.containsKey(person.Id)) {
                person.Total_Amount_of_Tasks__c = personsIdsToTasksIds.get(person.Id).size();    
            }else {
                person.Total_Amount_of_Tasks__c = 0;   
            }
        }
        
        update personsToUpdate;        
    }

    public static void setProjectStatusesBasedOnTasks(Set<Id> projectsIds){
    
        if(projectsIds.size() == 0){
            return;
        }


        List<Project__c> projects = [SELECT Id, Planned_End_Date__c, Status__c, 
                                        (SELECT Id, Status__c, End_Date__c FROM Tasks__r) 
                                    FROM Project__c 
                                    WHERE Id IN : projectsIds];

        for(Project__c project : projects){
            project.Status__c = ToDoListService.getProjectStatus(project.Tasks__r, project.Planned_End_Date__c);        
        }
        
        update projects;
    }

    public static Set<Id> getPersonsIds(List<Task__c> tasks){
        
        Set<Id> personsIds = new Set<Id>();

        for(Task__c task : tasks){
            
            if(task.Person__c == null){
                continue;
            }

            personsIds.add(task.Person__c);    
        }

        return personsIds;    
    }

    public static Set<Id> getProjectsIds(List<Task__c> tasks){

        Set<Id> projectsIds = new Set<Id>();

        for(Task__c task : tasks){
            projectsIds.add(task.Project__c);    
        }

        return projectsIds;    
    }

}