force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Project will start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date when Task is planned to start</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ToDoListService.cls
public class ToDoListService {
    
    public static String getProjectStatus(List<Task__c> tasks, Date projectPlanedEndDate){

        Integer completedStatusCount    = 0;
        Boolean taskCompletedWithDelay  = false;
        Boolean isInProgress            = false;

        for(Task__c task : tasks){

            if(task.Status__c == 'Started'){
                
                isInProgress = true;
                break;

            }else if(task.Status__c == 'Completed'){
                
                completedStatusCount += 1;

                if(task.End_Date__c > projectPlanedEndDate){
                    taskCompletedWithDelay = true;    
                } 
            }
        }


        if(isInProgress){
            return 'In Progress';
        }else if(tasks.size() == completedStatusCount){
            return taskCompletedWithDelay ? 'Finished with Delay' : 'Finished in Time';
        }else{
            return 'Draft';   
        }

    }

    public static void createPerson(String fName, String lName){

        Person__c person = New Person__c(First_Name__c = fName, Last_Name__c = lName);

        insert Person__c;
    }

    public static startNewTask(Id projectId, Id personId){

        Task__c task = new Task__c( 
                                    Project__c = projectId,
                                    Person__c  = personId,
                                    Status__c = 'Draft',
                                    Start_Date__c = System.today());

    }

    public static updateTaskStatusesForProject(Id projectId, String newStatus){
        
        List<Task__c> tasks = [SELECT Id, Status__c FROM Task__c WHERE Project__c =: projectId];
        for(Task__c task : tasks){
            task.Status__c = newStatus;    
        }

        update tasks;

    }

    public status deleteProjects(Set<Id> projectIds){

        List<Project__c> projects = [SELECT Id FROM Project__c WHERE Id IN : projectIds];

        delete projects;

    }
 

}