force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project to be completed</description>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Finished In Time</fullName>
            </value>
            <value>
                <fullName>Finished With Delay</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date when Task is planned to be finished</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Task Name</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Project that Task is Assigned to</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static Project__c createProject(String projectName){

        return new Project__c(
                                Name = projectName, 
                                Status__c = 'In Progress');
    }

    public static Task__c createStandardTask(Id projectId, Id personId, String status, Date endDate){

        return new Task__c(
                            Label__c = 'Standart Task', 
                            Status__c = status, 
                            Project__c = projectId,
                            Person__c  = personId, 
                            End_Date__c = endDate);                           
    }

    public static Task__c createOverdueTask(Id projectId, Id personId){

        return new Task__c(
                            Label__c = 'Overdue Task', 
                            Status__c = 'Started', 
                            Project__c = projectId,
                            Person__c  = personId, 
                            End_Date__c = System.today().addDays(-10));                           
    }

    public static Person__c createPerson(String firsName){

        return New Person__c(
                            First_Name__c = firsName);
    }

    public static List<Task__c> createProjectsWithTasks(Integer numProjects, Integer numTasksOfProj, Id personId, String taskStatus){

        List<Project__c> projects = new List<Project__c>();
        
        for(Integer i=0; i < numProjects; i++) {
            projects.add(
                createProject('Test')
            );
        }

        insert projects;

        List<Task__c> tasks = new List<Task__c>();
        

        for (Integer j=0;j<numProjects;j++) {
            
            Project__c project = projects[j];
            
            for (Integer k=0; k<numTasksOfProj; k++) {
                tasks.add(
                    TestDataFactory.createStandardTask(project.Id, 
                                                        personId, 
                                                        taskStatus == null ? 'Started' : taskStatus, 
                                                        System.today().addMonths(1))
                );
            }
        }
        
        insert tasks;
        
        return tasks;
    }

    public static List<Task__c> createTasksForProject(Id projectId, Id personId, Integer numTasksOfProj, String status, Date endDate){

        List<Task__c> tasks = new List<Task__c>();
        
        for(Integer i=0; i < numTasksOfProj; i++) {
            tasks.add(
                createStandardTask(projectId, personId, status, endDate)
            );
        }

        return tasks;
    }

    


}