force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name</description>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Projects__c</fullName>
    <description>Total amount of Projects assigned to Person</description>
    <label>Total Amount of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PersonControllerREST.cls
@RestResource(urlMapping='/Person/highestNumberOfAssignedProjects')
global  with sharing class PersonControllerREST {
    
    @HttpGet
    global static List<Person__c> getHighestNumberOfAssignedProjects() {
        
        List<Person__c> result = [SELECT First_Name__c, Last_Name__c, Total_Amount_of_Projects__c  
                                  FROM Person__c 
                                  ORDER BY Total_Amount_of_Projects__c DESC 
                                  LIMIT 5];
        
        return result;
    }

}