force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CheckEnteredValuesForTaskTest.cls
@isTest
public class CheckEnteredValuesForTaskTest {

    @isTest static void testCanNotChangePersonInCompletedTasks() {

        Person__c person1 = TestDataFactory.createPerson('TestPerson');
        insert person1;

        Person__c person2 = TestDataFactory.createPerson('TestPerson');
        insert person2;

        List<Task__c> tasks = TestDataFactory.createProjectsWithTasks(1, 100, person1.id, ToDoListService.Task_Status_Completed);

        System.assert(tasks.size() == 100, 'Expected 100 tasks');


        tasks = TestDataUtils.changePersonInTasks(tasks, person2.Id);


        Test.startTest();
            Database.SaveResult[] srList = Database.update(tasks, false);
        Test.stopTest();


        for (Database.SaveResult sr : srList) {
            
            System.assert(!sr.isSuccess());
            System.assert(sr.getErrors().size() > 0);
            System.assertEquals('Сan\'t change the personа of a completed task',
                                sr.getErrors()[0].getMessage());
        }

    }

    
    @isTest static void testChangePersonInNotCompletedTasks() {

        Person__c person1 = TestDataFactory.createPerson('TestPerson');
        insert person1;

        Person__c person2 = TestDataFactory.createPerson('TestPerson');
        insert person2;

        List<Task__c> tasks = TestDataFactory.createProjectsWithTasks(1, 100, person1.id, ToDoListService.Task_Status_Draft);

        System.assert(tasks.size() == 100, 'Expected 100 tasks');

        
        tasks = TestDataUtils.changePersonInTasks(tasks, person2.Id);


        Test.startTest();
            Database.SaveResult[] srList = Database.update(tasks, false);
        Test.stopTest();


        for (Database.SaveResult sr : srList) {
            System.assert(sr.isSuccess());
        }
    }
    
}