force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Person that is assigned to particular Task</description>
    <label>Person</label>
    <nameField>
        <displayFormat>P-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Projects__c</fullName>
    <description>Total amount of Projects assigned to Person</description>
    <label>Total Amount of Projects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Person__c/fields/Total_Amount_of_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_Tasks__c</fullName>
    <description>Total amount of Tasks assigned to Person</description>
    <label>Total Amount of Tasks</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <description>Task that is part of Project (Project can have up to 20 tasks)</description>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Person__c.field-meta.xml
<CustomField>
    <fullName>Person__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Person responsible for Task</description>
    <label>Person</label>
    <referenceTo>Person__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CalculTotTasksAndTotProjectsOfPersTest.cls
@isTest
public class CalculTotTasksAndTotProjectsOfPersTest {
   
    static Id personId;
    
    @testSetup
    static void setup() {

        Person__c person = TestDataFactory.createPerson('TestPerson');
        insert person;

        List<Task__c> tasks = TestDataFactory.createProjectsWithTasks(10, 15, person.id, null);
    }

    @isTest
    public static void calculateTotalTasksAndTotalProjectsOnAfterInsert(){
        
        Person__c person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];

        System.assertNotEquals(null, person, 'Object not found');
        
        System.assertEquals(10, person.Total_Amount_of_Projects__c, 'The total number of projects does not match');

        System.assertEquals(150, person.Total_Amount_of_Tasks__c, 'The total number of tasks does not match');
    }

    @isTest
    public static void calculateTotalTasksAndTotalProjectsOnAfterUpdate(){
        
        Person__c person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];

        Test.startTest();
            //Create new projects and task
            List<Task__c> tasks = TestDataFactory.createProjectsWithTasks(5, 15, person.id, null);
        Test.stopTest();

        person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];


        System.assertNotEquals(null, person, 'Object not found');
        
        System.assertEquals(15, person.Total_Amount_of_Projects__c, 'The total number of projects does not match');

        System.assertEquals(225, person.Total_Amount_of_Tasks__c, 'The total number of tasks does not match');
    }

    @isTest
    public static void calculateTotalTasksAndTotalProjectsOnAfterUpdate_DeletePersonFromTask(){
        
        Person__c person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];

        //delete 10 tasks
        Test.startTest();
            TestDataUtils.deletePersonsFromTasks(person.id);
        Test.stopTest();

        person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];

        System.assertNotEquals(null, person, 'Object not found');
        
        System.assertEquals(0, person.Total_Amount_of_Projects__c, 'The total number of projects does not match');

        System.assertEquals(0, person.Total_Amount_of_Tasks__c, 'The total number of tasks does not match');
    }

    @isTest
    public static void calculateTotalTasksAndTotalProjectsOnAfterDelete(){
        
        Person__c person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];


        System.assertNotEquals(null, person, 'Object not found');
        
        System.assertEquals(10, person.Total_Amount_of_Projects__c, 'The total number of projects does not match');

        System.assertEquals(150, person.Total_Amount_of_Tasks__c, 'The total number of tasks does not match');


        //delete 10 tasks
        Test.startTest();
            TestDataUtils.deleteTasksFromProjects(2, 5, person.id);
        Test.stopTest();    

        person = [SELECT Id, Total_Amount_of_Projects__c, Total_Amount_of_Tasks__c FROM Person__c LIMIT 1];

        System.assertEquals(10, person.Total_Amount_of_Projects__c, 'The total number of projects does not match');

        System.assertEquals(140, person.Total_Amount_of_Tasks__c, 'The total number of tasks does not match');
    }

}